create database Hotel;
show databases;
use hotel;
create table Reservation(
	ID int,
    Name varchar(30),
    ReserveDate Date,
    RoomNum Int
    );
show tables;
ALTER DATABASE Hotel CHARACTER SET=utf8 COLLATE=utf8_general_ci;
alter table test add phone int;
alter table test drop phone;
alter table test modify column ReserveDate varchar(20);
desc test;
use nodejs;
truncate table test;
DROP TABLE IF EXISTS Reservation;
alter table test add name varchar(20);
insert into test(id, Name, ReserveDate, RoomNum) values (1, '홍길동', '2016-01-05', 2014);
insert into test(id, Name, ReserveDate, RoomNum) values (2, '김철수', '2016-01-08', 2012);
insert into test(id, Name, ReserveDate, RoomNum) values (3, '이영희', '2016-01-05', 2012);
insert into test(id, Name, ReserveDate, RoomNum) values (4, '안동구', '2016-01-05', 2014);
insert into test(id, Name, ReserveDate, RoomNum, roomtype) values (5, '홍길동', '2016-01-10', 2015, 1);
alter table test modify column Name varchar(50) character set utf8;
alter table test character set=utf8;
update test set RoomNum=2003 where name='홍길동';
delete from test where name='홍길동';
SELECT * FROM test WHERE ID <= 3 AND ReserveDate > '2016-02-01';
select distinct name from test;
select * from test order by reserveDate desc;
SELECT ReserveDate, CONCAT(RoomNum, " : ", Name) AS ReserveInfo FROM test;
alter table test add price int;
desc test;
update test set price=1000;
select * from test;
alter table test modify column RoomNum decimal(7,2);
alter table test add note char(4);
insert into test (note) values ('abcdef');
ALTER TABLE test ADD COLUMN RoomType ENUM('Single', 'Twin', 'Double', 'Triple');
select * from test; 
ALTER TABLE test ADD COLUMN Request SET('Breakfast', 'Extra Bed', 'Non-Smoking');
insert into test(id, Name, ReserveDate, RoomNum, roomtype, request) values (5, '홍길동', '2016-01-10', 2015, 1, 'breakfast,non-smoking');
ALTER TABLE test MODIFY COLUMN ReserveDate DATETIME;
insert into test (reserveDate) values ('2020-02-13 14:21:30');
ALTER TABLE test ADD COLUMN CheckIn TIME;
insert into test (checkin) values (now());
ALTER TABLE test ADD COLUMN ThisYear YEAR;
select * from test;
insert into test (thisYear) value (20);
select 504.7 + 13, 504.7 * 0.9, 504.7 / 2, 504.7 div 2, 504.7 % 2; 
select 3=3, 0=null, 1=true, 1 is null, 3 between 2 and 7, 5 in (2,3,4,5);
SELECT CASE 0 WHEN 0 THEN 'zero' WHEN 1 THEN 'one' ELSE 'more' END ;
SELECT IF(0 < 1, 'yes', 'no');
SELECT * FROM test WHERE Name LIKE '홍%';
SELECT * FROM test WHERE Name not LIKE '홍%';
SELECT * FROM test WHERE Name LIKE '홍__';
SELECT * FROM test WHERE Name REGEXP '^홍|산$';
desc test;
select * from test;
alter table test add column nick varchar(50) not null;
insert into test (name, nick) value ('홍길동', '번쩍');
insert into test (name) value ('가나다');
insert into test (name, nick) value ('두번째', '번쩍');
alter table test add column age int not null;
alter table test modify column age int not null default 0;
insert into test (name, nick) value ('두번째', '번쩍');
select * from test;
alter table test add column email varchar(20) unique;
desc test;
insert into test (nick, email) value ('단무지', 'agc@aa.com');
insert into test (nick) value ('바람');
select * from test;
delete from test where id=5;
alter table Reservation modify column id int primary key;
select * from reservation;
alter table test add constraint aaa primary key (c_id);
alter table test modify column id int not null;
select * from test;
alter table test add column c_id int not null auto_increment primary key;
select * from test;
